{{- if and (or .Values.redis.password .Values.redis.username) (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-gateway.secretName" . }}
  labels:
    {{- include "ocean-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.username }}
  REDIS_USERNAME: {{ .Values.redis.username | b64enc | quote }}
  {{- end }}
{{- end }}
